name: WCA Runner Multiple (Dev)

on:
  workflow_dispatch:

jobs:
  wca-runner-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest || echo "No image found"

      - name: Run Docker container
        run: |
          docker run --rm \
            -e EVENT_URL="${{ secrets.EVENT_URL || '' }}" \
            -e WCA_ID="${{ secrets.WCA_ID || '' }}" \
            -e BIRTHDAY_YEAR="${{ secrets.BIRTHDAY_YEAR || '' }}" \
            -e BIRTHDAY_MONTH="${{ secrets.BIRTHDAY_MONTH || '' }}" \
            -e BIRTHDAY_DAY="${{ secrets.BIRTHDAY_DAY || '' }}" \
            -e EMAIL="${{ secrets.EMAIL || '' }}" \
            -e PHONE="${{ secrets.PHONE || '' }}" \
            -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN || '' }}" \
            -e DISCORD_GUILD_ID="${{ secrets.DISCORD_GUILD_ID || '' }}" \
            -e DISCORD_CHANNEL_ID="${{ secrets.DISCORD_CHANNEL_ID || '' }}" \
            -e NO_UI=false \
            ghcr.io/${{ github.repository }}:latest || echo "Some arguments might be missing"

  wca-runner-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest || echo "No image found"

      - name: Run Docker container
        run: |
          docker run --rm \
            -e EVENT_URL="${{ secrets.EVENT_URL || '' }}" \
            -e WCA_ID="${{ secrets.WCA_ID || '' }}" \
            -e BIRTHDAY_YEAR="${{ secrets.BIRTHDAY_YEAR || '' }}" \
            -e BIRTHDAY_MONTH="${{ secrets.BIRTHDAY_MONTH || '' }}" \
            -e BIRTHDAY_DAY="${{ secrets.BIRTHDAY_DAY || '' }}" \
            -e EMAIL="${{ secrets.EMAIL || '' }}" \
            -e PHONE="${{ secrets.PHONE || '' }}" \
            -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN || '' }}" \
            -e DISCORD_GUILD_ID="${{ secrets.DISCORD_GUILD_ID || '' }}" \
            -e DISCORD_CHANNEL_ID="${{ secrets.DISCORD_CHANNEL_ID || '' }}" \
            -e NO_UI=false \
            ghcr.io/${{ github.repository }}:latest || echo "Some arguments might be missing"

  wca-runner-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest || echo "No image found"

      - name: Run Docker container
        run: |
          docker run --rm \
            -e EVENT_URL="${{ secrets.EVENT_URL || '' }}" \
            -e WCA_ID="${{ secrets.WCA_ID || '' }}" \
            -e BIRTHDAY_YEAR="${{ secrets.BIRTHDAY_YEAR || '' }}" \
            -e BIRTHDAY_MONTH="${{ secrets.BIRTHDAY_MONTH || '' }}" \
            -e BIRTHDAY_DAY="${{ secrets.BIRTHDAY_DAY || '' }}" \
            -e EMAIL="${{ secrets.EMAIL || '' }}" \
            -e PHONE="${{ secrets.PHONE || '' }}" \
            -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN || '' }}" \
            -e DISCORD_GUILD_ID="${{ secrets.DISCORD_GUILD_ID || '' }}" \
            -e DISCORD_CHANNEL_ID="${{ secrets.DISCORD_CHANNEL_ID || '' }}" \
            -e NO_UI=false \
            ghcr.io/${{ github.repository }}:latest || echo "Some arguments might be missing"

  wca-runner-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest || echo "No image found"

      - name: Run Docker container
        run: |
          docker run --rm \
            -e EVENT_URL="${{ secrets.EVENT_URL || '' }}" \
            -e WCA_ID="${{ secrets.WCA_ID || '' }}" \
            -e BIRTHDAY_YEAR="${{ secrets.BIRTHDAY_YEAR || '' }}" \
            -e BIRTHDAY_MONTH="${{ secrets.BIRTHDAY_MONTH || '' }}" \
            -e BIRTHDAY_DAY="${{ secrets.BIRTHDAY_DAY || '' }}" \
            -e EMAIL="${{ secrets.EMAIL || '' }}" \
            -e PHONE="${{ secrets.PHONE || '' }}" \
            -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN || '' }}" \
            -e DISCORD_GUILD_ID="${{ secrets.DISCORD_GUILD_ID || '' }}" \
            -e DISCORD_CHANNEL_ID="${{ secrets.DISCORD_CHANNEL_ID || '' }}" \
            -e NO_UI=false \
            ghcr.io/${{ github.repository }}:latest || echo "Some arguments might be missing"

  wca-runner-5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest || echo "No image found"

      - name: Run Docker container
        run: |
          docker run --rm \
            -e EVENT_URL="${{ secrets.EVENT_URL || '' }}" \
            -e WCA_ID="${{ secrets.WCA_ID || '' }}" \
            -e BIRTHDAY_YEAR="${{ secrets.BIRTHDAY_YEAR || '' }}" \
            -e BIRTHDAY_MONTH="${{ secrets.BIRTHDAY_MONTH || '' }}" \
            -e BIRTHDAY_DAY="${{ secrets.BIRTHDAY_DAY || '' }}" \
            -e EMAIL="${{ secrets.EMAIL || '' }}" \
            -e PHONE="${{ secrets.PHONE || '' }}" \
            -e DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN || '' }}" \
            -e DISCORD_GUILD_ID="${{ secrets.DISCORD_GUILD_ID || '' }}" \
            -e DISCORD_CHANNEL_ID="${{ secrets.DISCORD_CHANNEL_ID || '' }}" \
            -e NO_UI=false \
            ghcr.io/${{ github.repository }}:latest || echo "Some arguments might be missing"